server:
  port: 0

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data;DB_CLOSE_ON_EXIT=FALSE
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 1
      minimum-idle: 1
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false
